### ISSUE TITLE
Adding CloudSlang, Verigreen and Image Lifecycle Management to the list of top_os_projects.md

### ISSUE THREAD

**Issue by eitansch** [MoradST/HPEOpenSource#3]
Hi @whomper - shouldn't we add the following projects as well?
- [CloudSlang](http://cloudslang.io/#/), [project code](https://github.com/CloudSlang)
- [Verigreen](http://verigreen.io), [project code](http://github.com/Verigreen)
- [(Docker) Image Lifecycle Management - project code](https://github.com/eedevops)

**Comment by whomper** [comment]
yeah, I focused on the big communities, but clearly the two you brought up make perfect sense. Feel free to update.

**Comment by MoradST** [comment]
Awesome!

**Comment by eitansch** [comment]
Updated to reflect the two upper projects. Once we have ILM out there I'll update it as well (June-ish :smile:)
